In [74]:

# prompt: One hot encoding pada bagian hasil

import pandas as pd
df = pd.read_csv('/content/DataBola2.csv') # Reload the original DataFrame
df = pd.get_dummies(df, columns=['Hasil'], prefix=['Hasil'])
print(df)

    No      Team          Team_Lawan  Goal_Team  Goal_Team_Lawan  \
0    1  Indonesia            Bahrain          2                2
1    2  Indonesia          Australia          0                0
2    3  Indonesia      Saudia Arabia          1                1
3    4  Indonesia        Philippines          2                0
4    5  Indonesia               Iraq          0                2
5    6  Indonesia            Vietnam          3                0
6    7  Indonesia            Vietnam          1                0
7    8  Indonesia        Philippines          1                1
8    9  Indonesia               Iraq          1                5
9   10  Indonesia  Bruneu Darussalam          6                0
10  11  Indonesia  Bruneu Darussalam          6                0
11  12     China           Australia          1                3
12  13     China              Jepang          0                7
13  14     China           Singapura          4                1
14  15     China           Singapura          2                2
15  16     China       Saudia Arabia          1                2
16  17  Indonesia              China          1                1
17  18  Indonesia              China          0                5
18  19  Indonesia              China          0                2
19  20  Indonesia              China          1                5

    Hasil_Imbang  Hasil_Kalah  Hasil_Menang
0           True        False         False
1           True        False         False
2           True        False         False
3          False        False          True
4          False         True         False
5          False        False          True
6          False        False          True
7           True        False         False
8          False         True         False
9          False        False          True
10         False        False          True
11         False         True         False
12         False         True         False
13         False        False          True
14          True        False         False
15         False         True         False
16          True        False         False
17         False         True         False
18         False         True         False
19         False         True         False

In [75]:
df

,No,Team,Team_Lawan,Goal_Team,Goal_Team_Lawan,Hasil_Imbang,Hasil_Kalah,Hasil_Menang
0,1,Indonesia,Bahrain,2,2,True,False,False
1,2,Indonesia,Australia,0,0,True,False,False
2,3,Indonesia,Saudia Arabia,1,1,True,False,False
3,4,Indonesia,Philippines,2,0,False,False,True
4,5,Indonesia,Iraq,0,2,False,True,False
5,6,Indonesia,Vietnam,3,0,False,False,True
6,7,Indonesia,Vietnam,1,0,False,False,True
7,8,Indonesia,Philippines,1,1,True,False,False
8,9,Indonesia,Iraq,1,5,False,True,False
9,10,Indonesia,Bruneu Darussalam,6,0,False,False,True
10,11,Indonesia,Bruneu Darussalam,6,0,False,False,True
11,12,China,Australia,1,3,False,True,False
12,13,China,Jepang,0,7,False,True,False
13,14,China,Singapura,4,1,False,False,True
14,15,China,Singapura,2,2,True,False,False
15,16,China,Saudia Arabia,1,2,False,True,False
16,17,Indonesia,China,1,1,True,False,False
17,18,Indonesia,China,0,5,False,True,False
18,19,Indonesia,China,0,2,False,True,False
19,20,Indonesia,China,1,5,False,True,False

In [76]:
import pandas as pd

# Cek apakah kolom 'Team' dan 'Team_Lawan' ada dalam DataFrame
if 'Team' in df.columns and 'Team_Lawan' in df.columns:
    df = pd.get_dummies(df, columns=['Team', 'Team_Lawan'], prefix=['Team', 'Team_Lawan'])
    print(df)
else:
    print("Kolom 'Team' atau 'Team_Lawan' tidak ditemukan dalam DataFrame.")

Kolom 'Team' atau 'Team_Lawan' tidak ditemukan dalam DataFrame.

In [77]:
import pandas as pd

# Contoh DataFrame (gantilah dengan DataFrame asli Anda)
data = {
    'Team': ['China', 'Australia', 'Japan'],
    'Team_Lawan': ['Japan', 'China', 'Australia'],
    'Goal_Team': [1, 0, 3],
    'Goal_Team_Lawan': [2, 1, 0]
}
df = pd.DataFrame(data)

# Cek nama kolom
print("Nama kolom dalam DataFrame:")
print(df.columns.tolist())

# Bersihkan nama kolom
df.columns = df.columns.str.strip()
print("Nama kolom setelah dibersihkan:")
print(df.columns.tolist())

# Pastikan kolom 'Team' dan 'Team_Lawan' ada
if 'Team' in df.columns and 'Team_Lawan' in df.columns:
    df = pd.get_dummies(df, columns=['Team', 'Team_Lawan'], prefix=['Team', 'Team_Lawan'])
    print("DataFrame setelah one-hot encoding:")
    print(df.head())
else:
    print("Kolom 'Team' atau 'Team_Lawan' tidak ditemukan dalam DataFrame.")

Nama kolom dalam DataFrame:
['Team', 'Team_Lawan', 'Goal_Team', 'Goal_Team_Lawan']
Nama kolom setelah dibersihkan:
['Team', 'Team_Lawan', 'Goal_Team', 'Goal_Team_Lawan']
DataFrame setelah one-hot encoding:
   Goal_Team  Goal_Team_Lawan  Team_Australia  Team_China  Team_Japan  \
0          1                2           False        True       False
1          0                1            True       False       False
2          3                0           False       False        True

   Team_Lawan_Australia  Team_Lawan_China  Team_Lawan_Japan
0                 False             False              True
1                 False              True             False
2                  True             False             False

In [78]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Contoh DataFrame (gantilah dengan DataFrame asli Anda)
data = {
    'Team': ['China', 'Australia', 'Japan', 'China', 'Australia'],
    'Team_Lawan': ['Japan', 'China', 'Australia', 'Australia', 'Japan'],
    'Goal_Team': [1, 2, 3, 1, 2],
    'Goal_Team_Lawan': [2, 1, 0, 3, 1]
}
df = pd.DataFrame(data)

# Pastikan kolom 'Team' dan 'Team_Lawan' ada dan lakukan one-hot encoding
df.columns = df.columns.str.strip()  # Bersihkan nama kolom
if 'Team' in df.columns and 'Team_Lawan' in df.columns:
    df = pd.get_dummies(df, columns=['Team', 'Team_Lawan'], prefix=['Team', 'Team_Lawan'])
else:
    print("Kolom 'Team' atau 'Team_Lawan' tidak ditemukan dalam DataFrame.")

# Memisahkan fitur (X) dan target (y)
X = df.drop(['Goal_Team', 'Goal_Team_Lawan'], axis=1)  # Fitur
y = df['Goal_Team']  # Target, menggunakan salah satu kolom target

# Membagi data menjadi data latih dan data uji
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Membuat model machine learning
models = {
    'Logistic Regression': LogisticRegression(max_iter=200),
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(),
    'Support Vector Machine': SVC(),
    'K-Nearest Neighbors': KNeighborsClassifier(n_neighbors=3)  # Mengatur n_neighbors menjadi 3
}

# Melatih dan mengevaluasi model
results = {}
for model_name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    results[model_name] = accuracy

# Menampilkan hasil
print("Hasil Evaluasi Model:")
for model_name, accuracy in results.items():
    print(f"{model_name}: {accuracy:.2f}")

# Menentukan model terbaik
best_model = max(results, key=results.get)
print(f"\nModel Terbaik: {best_model} dengan akurasi {results[best_model]:.2f}")

Hasil Evaluasi Model:
Logistic Regression: 1.00
Decision Tree: 0.00
Random Forest: 1.00
Support Vector Machine: 0.00
K-Nearest Neighbors: 0.00

Model Terbaik: Logistic Regression dengan akurasi 1.00

In [79]:
# prompt: gunakan Model Terbaik: Logistic Regression dengan akurasi sebagai model

# Model terbaik adalah Logistic Regression, jadi kita akan menggunakannya
model = LogisticRegression(max_iter=200)

# Melatih model dengan seluruh data pelatihan
model.fit(X_train, y_train)

# Contoh penggunaan model untuk prediksi (gantilah dengan data baru yang ingin diprediksi)
new_data = X_test.iloc[[0]]  # Misalnya, menggunakan data pertama dari data uji
prediction = model.predict(new_data)

print(f"Prediksi untuk data baru: {prediction[0]}")

Prediksi untuk data baru: 2

In [80]:
import pandas as pd

# Buat data baru untuk prediksi
new_data = pd.DataFrame({
    'Team_Indonesia': [1],
    'Team_China': [1],
    'Team_Australia': [0],
    'Team_Japan': [0],
    'Team_Lawan_Indonesia': [0],
    'Team_Lawan_China': [1],
    'Team_Lawan_Australia': [0],
    'Team_Lawan_Japan': [0]
})

# Pastikan urutan kolom data baru sama dengan urutan kolom X_train
new_data = new_data[X_train.columns]

# Lakukan prediksi
prediction = model.predict(new_data)

# Asumsikan model memprediksi 0: kalah, 1: imbang, 2: menang
result_mapping = {0: "Kalah", 1: "Imbang", 2: "Menang"}
predicted_result = result_mapping[prediction[0]]

print(f"Prediksi hasil pertandingan Indonesia melawan China: {predicted_result}")

Prediksi hasil pertandingan Indonesia melawan China: Imbang